In [195]:
import sys
sys.path.insert(0,"/Users/jean-mariemirebeau/Dropbox/Programmes/GithubM1/AGDT/AdaptiveGridDiscretizations_Taichi")
import taichi as ti
import numpy as np
ti.init()


[Taichi] Starting on arch=arm64


In [196]:
from agdt import GetArrayModule

In [317]:
pack_t = ti.types.argpack(u=ti.math.vec2,v=float)
pack = pack_t(u=[1,2],v=3)
pack.f = lambda x : 2*x
pack.f(2)itunes

4

In [318]:
arr = ti.ndarray(float,4)
arr[0]=1

arr_np = arr.to_numpy() # Copies
arr_np[0]=2
arr[0]

1.0

In [320]:
help(arr.copy_from)

Help on method copy_from in module taichi.lang._ndarray:

copy_from(other) method of taichi.lang._ndarray.ScalarNdarray instance
    Copies all elements from another ndarray.

    The shape of the other ndarray needs to be the same as `self`.

    Args:
        other (Ndarray): The source ndarray.



In [319]:
x=2
if (y:=x) is None: print("None")
else: print(y)

2


In [280]:
#offset_t = 
@ti.kernel
def testdiv():
    e = ti.math.ivec2([-1,2])
    f = e/e.sum()
    print(e,f)
    E = ti.lang.matrix.VectorType(2,ti.i8)(-1,2)
    print(ti.abs(e).max())
    print(ti.i32(4)%ti.i32(3))
testdiv()

[-1, 2] [-1.000000, 2.000000]
2
1


In [270]:
ti.select(False,2,3)

np.int64(3)

In [281]:
ms = ti.field(ti.math.mat2,shape=tuple())
ms.fill(np.eye(2).tolist())
ms[None]

[[1. 0.]
 [0. 1.]]

In [293]:
arr = ti.field(float,(3,3))
arr.from_numpy(np.arange(9).reshape((3,3)))
arr.to_numpy()#.max()
ti.max(arr).to_numpy()

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

In [296]:
ti.i16

In [242]:
@ti.pyfunc
def zero_like(x):
    y = x-x
    y.fill(0)
    return y

vec_t = ti.lang.matrix.VectorType(2,ti.i8) 
x = vec_t(20,30)
x0 = zero_like(x)
x0[0]+=40
print(x0,x)

@ti.kernel
def testzero():
    x = vec_t(20,30)
    x0 = zero_like(x)
    x0[1]+=40
    print(x0)
    print(x)
    x1 = ti.zero(x0)
    x1[0]+=120; x1[0]*=2
    print(x1)
testzero()

[-96 120] [20 30]
[120, -96]
[20, 30]
[240, 0]


/var/folders/pr/ywmc0vdj1_q45y494__w0nsr0000gn/T/ipykernel_13272/2674164701.py:10: RuntimeWarning: overflow encountered in scalar add
  x0[0]+=40
[W 09/17/25 17:40:12.704 351194] TaichiWarning
File "/var/folders/pr/ywmc0vdj1_q45y494__w0nsr0000gn/T/ipykernel_13272/2674164701.py", line 17, in testzero:
    x0[1]+=40
    ^^^^^^^^^
Atomic add may lose precision: i8 <- i32
[W 09/17/25 17:40:12.707 351194] TaichiWarning
While compiling `testzero_c188_0`, File "/Users/jean-mariemirebeau/opt/miniconda3/envs/agdt_313/lib/python3.13/site-packages/taichi/lang/matrix_ops.py", line 255, in fill:
            mat[i] = val
            ^^^^^^^^^^^^
Assign may lose precision: i8 <- i32
[W 09/17/25 17:40:12.707 351194] TaichiWarning
While compiling `testzero_c188_0`, File "/Users/jean-mariemirebeau/opt/miniconda3/envs/agdt_313/lib/python3.13/site-packages/taichi/lang/matrix_ops.py", line 255, in fill:
            mat[i] = val
            ^^^^^^^^^^^^
Assign may lose precision: i8 <- i32


In [222]:
@ti.pyfunc
def cast_vec(x,dtype:ti.template()):
    y = dtype(0)
    y = dtype(x)
    return y

@ti.pyfunc
def cast_scal(x,dtype:ti.template()):
    y:dtype = 0
    y = dtype(x)
    return y

vec = ti.math.vec2([2.4,120.5]); vec_t = ti.lang.matrix.VectorType(2,ti.i8) # vec_t = ti.math.ivec2
scal = 2.5; scal_t = ti.i32
#x = 2.5; dtype = ti.i32
py_iv = cast_vec(vec,vec_t)
py_iv[1]+=40
print("python",py_iv)
#print("python",cast_scal(scal,scal_t))

@ti.kernel
def testcast():
    iv = cast_vec(vec,vec_t)
    iv[1]+=40
    print(iv)
    print(cast_scal(scal,scal_t))
    print("ti cast",ti.cast(2.5,ti.i32))
testcast()

python [  2 -96]
[2, -96]
2
ti cast 2


/var/folders/pr/ywmc0vdj1_q45y494__w0nsr0000gn/T/ipykernel_13272/4002666701.py:17: RuntimeWarning: overflow encountered in scalar add
  py_iv[1]+=40
[W 09/17/25 17:31:21.420 351194] TaichiWarning
File "/var/folders/pr/ywmc0vdj1_q45y494__w0nsr0000gn/T/ipykernel_13272/4002666701.py", line 24, in testcast:
    iv[1]+=40
    ^^^^^^^^^
Atomic add may lose precision: i8 <- i32


TypeError: element_type(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_python.DataType) -> taichi._lib.core.taichi_python.DataType

Invoked with: <taichi._lib.core.taichi_python.DataType object at 0x10982eef0>, 2

In [179]:
#vec = ti.math.vec3([1,-2,3.])
vec_t = ti.lang.matrix.VectorType(2,ti.i8)
vec = vec_t([127,-1])

@ti.kernel
def test():
    vec2 = ti.zero(vec)
    vec2[0]=129
    print(vec,vec2)
test()

[127, -1] [129, 0]


In [155]:
def f(x,y): return x+y
import inspect
len(inspect.signature(f).parameters)

2

In [159]:
[1,2,3].index(2)

1

In [160]:
help(list.index)

Help on method_descriptor:

index(self, value, start=0, stop=9223372036854775807, /) unbound builtins.list method
    Return first index of value.

    Raises ValueError if the value is not present.



In [163]:
vec = ti.math.vec3([1,2,3.])

AssertionError: determinant cannot be called in Python-scope

In [60]:
def area(self): return self.bla #4*np.pi*self.radius**2
Sphere = ti.types.struct(center=ti.math.vec3, radius=ti.f32,
                         __struct_methods={'area': area})

#Sphere.members['bla']=ti.f32
#sp= Sphere([0,0,1.],2.,3.)
#type(Sphere([0,0,1.],2.))
#sp = Sphere([0,0,1.],2.)



In [142]:
np.argmin([3,1,2])

np.int64(1)

In [134]:
test = ti.field(dtype=ti.math.vec2,shape=(2,2))
test.

1

In [138]:
arr1 = ti.field(dtype=ti.f32,shape=(2,2))
arr1.shape

(2, 2)

In [149]:
",".join(["x1","x2"])

'x1,x2'

In [152]:
[1,2].join(3)

AttributeError: 'list' object has no attribute 'join'

In [141]:
arr1[0,0].shape

AttributeError: 'float' object has no attribute 'shape'

In [103]:
@ti.dataclass
class Sphere:
    radius:ti.f32

    @ti.pyfunc
    def bli(self):
        return self.bla


Sphere.members['bla']=ti.f32
Sphere.blu = 3
#test = ti.field(dtype=Sphere,shape=(2,2))

@ti.kernel
def test():
    sp = Sphere(2.,5.)
    print(sp.bli())
    blu = ti.static(Sphere.blu)
test()

@ti.pyfunc
def test3(x):
    return x*x*x

test3.info = lambda x:'hello'


5.000000


In [119]:
arr = ti.math.vec2([1,2])
arr.n
arr.


[1. 2.]

In [124]:
ti.cos(2)

np.float64(-0.4161468365471424)

In [38]:
arr = ti.field(dtype=ti.f32,shape=10)
varr = ti.Vector.field(2,ti.i8,shape=(3,3))

In [76]:
def reshape_field(arr,shape,dtype=None): # Unclear how to do this properly in Taichi ...
    if dtype is None: dtype=arr.dtype; ishape=tuple()
    else: ishape = (dtype.n,dtype.m)
    res = ti.field(dtype,shape) # arr.dtype only retains the float/int type (ex : vec2->float)
    res.from_numpy(arr.to_numpy().reshape(shape+ishape))

dtype=ti.math.vec2
a = ti.field(dtype,shape=6)
reshape_field(a,(2,3,),dtype)

In [74]:
a.from_numpy(2*np.arange(12).reshape(6,2,1))

In [73]:
ti.math.vec2(0).m

1

In [8]:
arr[1]=1

In [10]:
arr.to_numpy()

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [17]:
np.prod(arr.shape)

np.int64(10)

In [22]:
np.unique([0,1,0,1])

array([0, 1])

In [24]:
from itertools import groupby
list(groupby( (0,2,3,2)))

[(0, <itertools._grouper at 0x1156bc190>),
 (2, <itertools._grouper at 0x1156be9b0>),
 (3, <itertools._grouper at 0x1156bcdf0>),
 (2, <itertools._grouper at 0x1156be350>)]

In [28]:
np.array([1,2,3])[slice(0,2)]

array([1, 2])

In [37]:
max(1,2,-3)

2

In [34]:
range(slice(0,2))

TypeError: 'slice' object cannot be interpreted as an integer

In [35]:
help(ti.lang.matrix.VectorType)

Help on class VectorType in module taichi.lang.matrix:

class VectorType(MatrixType)
 |  VectorType(n, dtype)
 |  
 |  Method resolution order:
 |      VectorType
 |      MatrixType
 |      taichi.types.compound_types.CompoundType
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args)
 |      Return a vector matching the shape and dtype.
 |      
 |      This function will try to convert the input to a `n`-component vector.
 |      
 |      Example::
 |      
 |          >>> vec3 = VectorType(3, float)
 |      
 |          Create from n scalars:
 |      
 |              >>> v = vec3(1, 2, 3)
 |      
 |          Create from a list/tuple of n scalars:
 |      
 |              >>> v = vec3([1, 2, 3])
 |      
 |          Create from a single scalar
 |      
 |              >>> v = vec3(1)
 |  
 |  __init__(self, n, dtype)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  field(self, **kwargs)
 |  
 |  ndarray(self, **kwargs)
 |